<a href="https://colab.research.google.com/github/bhanu0925/test/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
## TF Fundamentals

In [3]:
# import tensorflow

In [4]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.7.0


In [6]:
# creating tensors iwth tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# check the number of dimension of a tensor
scalar.ndim

0

In [8]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
# check the dimention of vector
vector.ndim

1

In [10]:
# create a matrix ( more then one dimesion)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
# create another matrix 
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# no of dimension of another_matrix
another_matrix.ndim

2

In [14]:
# lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
tensor.ndim

3

In [16]:
## Creating tensors with tf.Variable

## Creating tensors with tf.Variable

In [17]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
## try changing one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [20]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
## try changing one of the elements in our unchangeable tensor
unchangeable_tensor[0] =  7

TypeError: ignored

In [ ]:
unchangeable_tensor[0].assign(7)

## Creating random tensors

In [22]:
## create two random tensor(smae one)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
random_2 == random_1

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [25]:
## shuffling the order of elements in the tensor

In [26]:
## shuffel a tensor - valuable for when you want to shuffle your data so the inherent order does not affect learning
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [27]:
## shuffle or tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [28]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [29]:
## Other ways to make tensors

In [30]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [31]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [32]:
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [33]:
## also turn numpy array to tensor

In [34]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A
## X = tf.constant(some_matrix) // capital for matrix or tensor
## y = tf.constant(vector) // non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [35]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### getting information form tesors

* shape
* rank
* Axis or dimension
* size

In [36]:
## create a rank 4 tensor ( 4 D)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor, rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [37]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [38]:
rank_4_tensor[0].shape

TensorShape([3, 4, 5])

In [39]:
rank_4_tensor[0].ndim

3

In [40]:
tf.size(rank_4_tensor[0])

<tf.Tensor: shape=(), dtype=int32, numpy=60>

In [41]:
## get various attributes of our tensor

In [42]:
print("datatype : ",rank_4_tensor.dtype)
print("dimention",rank_4_tensor.ndim)
print("shape of tensor",rank_4_tensor.shape)
print("element alone 0 axis", rank_4_tensor.shape[0])
print("elemnt alone last index", rank_4_tensor.shape[-1])
print("total elements", tf.size(rank_4_tensor))
print("total elements", tf.size(rank_4_tensor).numpy())

datatype :  <dtype: 'float32'>
dimention 4
shape of tensor (2, 3, 4, 5)
element alone 0 axis 2
elemnt alone last index 5
total elements tf.Tensor(120, shape=(), dtype=int32)
total elements 120


In [43]:
### indexing tensors
##can be indexed just like lists

In [44]:
# get the first 2 elements of each dimention
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [45]:
# get the first elemnts form each dimention for each index except the final one

In [46]:
rank_4_tensor[:1,:1,:1,:5]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
## some operations

# create a rank 2 tensor (2 dimension)

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape , rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [48]:
# fetch teh last elemtn of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [49]:
# adding extra dimention to the tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [50]:
 ## alternative to tf.newaxis
 tf.expand_dims(rank_2_tensor, axis=-1) # -1 - expand the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [51]:
 tf.expand_dims(rank_2_tensor, axis=0) # 0 - expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [52]:
 tf.expand_dims(rank_2_tensor, axis=1) # 1 - expand the middle axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [53]:
### Manipulating tensors - tensor operation

# +,*,-,/

In [54]:
tensor = tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [55]:
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [56]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [57]:
## the original tensor is not changed

In [58]:
## multiplication

tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [59]:
## subtraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [60]:
## we can use tensor flow builtin function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [61]:
tf.add(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

In [62]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [63]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [64]:
### Matrix multiplication 

In [65]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [66]:
## Python operator @

tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [67]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [68]:
## how to make size compatiple for multiplication, innner dimensions
X = tf.constant([[3,4],[4,5],[5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 5],
       [5, 6]], dtype=int32)>

In [76]:
Y = tf.constant([[91,4],[11,5],[14,6]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[91,  4],
       [11,  5],
       [14,  6]], dtype=int32)>

In [77]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [78]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[91,  4, 11],
       [ 5, 14,  6]], dtype=int32)>

In [79]:
tf.matmul(X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[293,  68,  57],
       [389,  86,  74],
       [485, 104,  91]], dtype=int32)>

In [80]:
## also can be done with transpose
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[91, 11, 14],
       [ 4,  5,  6]], dtype=int32)>

In [81]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [4, 5, 6]], dtype=int32)>

In [84]:
tf.transpose(X), tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 5],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 4],
        [5, 5, 6]], dtype=int32)>)

In [85]:
## try mut mul with transpose then reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[387,  62],
       [503,  77]], dtype=int32)>

In [86]:
## the dot product

In [87]:
# can perform matmul using
# tf.matmul()
# tf.tensordot()

In [89]:
# perform the dot product on X and y  ( required x and y to be transposed)

tf.tensordot(tf.transpose(X),Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[387,  62],
       [503,  77]], dtype=int32)>

In [90]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[289,  53,  66],
       [384,  69,  86],
       [479,  85, 106]], dtype=int32)>

In [92]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[293,  68,  57],
       [389,  86,  74],
       [485, 104,  91]], dtype=int32)>

In [95]:
# check values of Y , shape of Y and transpose Y
print(" normal Y :", Y)
print(" Y reshaped (2,3)", tf.reshape(Y, shape=(2,3)))
print("transosed",tf.transpose(Y))

 normal Y : tf.Tensor(
[[91  4]
 [11  5]
 [14  6]], shape=(3, 2), dtype=int32)
 Y reshaped (2,3) tf.Tensor(
[[91  4 11]
 [ 5 14  6]], shape=(2, 3), dtype=int32)
transosed tf.Tensor(
[[91 11 14]
 [ 4  5  6]], shape=(2, 3), dtype=int32)


In [96]:
## Generally matrix multiplication , we will transpose , one of the matrix then reshape

In [97]:
## Changing the data types of a tensor

In [98]:
# create a new tensor with defualt dtype - float 32

In [100]:
B = tf.constant([1.7,7.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [101]:
C = tf.constant([7,4])
C
C.dtype

tf.int32

In [106]:
## change from float32 to float16

D = tf.cast(B, dtype= tf.float16)
D.dtype, D


(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>)

In [107]:
E = tf.cast(C, dtype=tf.float16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([7., 4.], dtype=float16)>,
 tf.float16)

In [109]:
## Aggregating
# aggregating tensor = condensing then from multiple values down to smaller amount of values

In [110]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [111]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [112]:
## forms of aggregation

In [114]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [115]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [116]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [117]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [121]:
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([36, 74, 47, 14, 96, 99, 44, 19, 33, 38, 73, 41, 55, 32,  8, 28, 96,
       58, 34, 67,  5, 83, 51, 66, 66, 97, 44, 17, 41, 95, 37, 36, 57, 75,
       49, 99, 83,  2,  3,  2,  4,  0, 19, 97, 66, 16, 95, 22, 87, 87])>

In [122]:
E.shape, E.ndim,tf.size(E)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [124]:
tf.reduce_max(E).numpy()

99

In [125]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [126]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [127]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2493>

In [128]:
## Find the variance and standard deviation

In [129]:
import tensorflow_probability as tfp

In [131]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=983>

In [143]:
## Standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.341352>

In [145]:
# find the variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=982.2804>

In [146]:
## positinal maximum and minimum of a tensor

In [148]:
# create a new tensor for finding positional minimum andmaximum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [149]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [150]:
# index on our larget position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [151]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [152]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [153]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [154]:
# find positional minimum
F[tf.argmin(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [156]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [157]:
## Squeezing tensors(removign all single dimensions)

In [158]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape = [1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [159]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [161]:
G_sqeez = tf.squeeze(G)
G_sqeez

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [162]:
## Onhot encoding tensors

In [163]:
# create a list of indices
some_list = [0,1,2,3]

In [164]:
# on hot encode
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [165]:
## specify custom values for one hot encoding

In [168]:
tf.one_hot(some_list,depth=3,on_value="yo i love deep learning",off_value='i also like to dance')

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like to dance',
        b'i also like to dance'],
       [b'i also like to dance', b'yo i love deep learning',
        b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'yo i love deep learning'],
       [b'i also like to dance', b'i also like to dance',
        b'i also like to dance']], dtype=object)>

In [169]:
### Squaring log, suareroot

In [171]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [172]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [174]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

## find log

In [176]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [177]:
## tensor and numpy compatability

In [178]:
# create a tensor for numpy

In [179]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [181]:
#convert tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [182]:
## convert tensor J to numpy array

In [183]:
J.numpy()

array([ 3.,  7., 10.])

In [184]:
## the default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5.,7.]))
tensor_J = tf.constant([3.,4.,5.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

**Finding GPU**

In [1]:
tf.config.list_physical_devices()

NameError: ignored

In [2]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Tue Nov 23 18:00:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    30W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------